services:
  db:
    image: postgres:18
    container_name: wetap-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: wetap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /data/wetap/postgres:/var/lib/postgresql/data
    networks:
      - wetap_net

  db-backup:
    image: prodrigestivill/postgres-backup-local:18
    container_name: wetap-db-backup
    restart: unless-stopped
    volumes:
      - /data/wetap/backups:/backups
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=wetap
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SCHEDULE=0 */6 * * *
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    networks:
      - wetap_net

  api:
    image: pedro007salo/wetap-api:latest
    container_name: wetap-api
    restart: unless-stopped
    volumes:
      - /data/wetap/media:/app/media
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Database=wetap;Username=postgres;Password=postgres
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    networks:
      - wetap_net

  web:
    image: pedro007salo/wetap-web:latest
    container_name: wetap-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - api
    networks:
      - wetap_net

networks:
  wetap_net:
    driver: bridge